# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kalman Filter with Lag 1 for State Space Models
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @details The measurement model is given by
#'   \deqn{
#'     \mathbf{y}_{t}
#'     =
#'     \boldsymbol{\nu}
#'     +
#'     \boldsymbol{\Lambda}
#'     \boldsymbol{\eta}_{t}
#'     +
#'     \boldsymbol{\varepsilon}_{t}
#'     \quad
#'     \mathrm{with}
#'     \quad
#'     \boldsymbol{\varepsilon}_{t}
#'     \sim
#'     \mathcal{N}
#'     \left(
#'     \mathbf{0},
#'     \boldsymbol{\Theta}
#'     \right)
#'   }
#'   where \eqn{\mathbf{y}_{t}}, \eqn{\boldsymbol{\eta}_{t}},
#'   and \eqn{\boldsymbol{\varepsilon}_{t}}
#'   are random variables and \eqn{\boldsymbol{\nu}},
#'   \eqn{\boldsymbol{\Lambda}},
#'   and \eqn{\boldsymbol{\Theta}} are model parameters.
#'   \eqn{\mathbf{y}_{t}} is a vector of observed random variables
#'   at time \eqn{t},
#'   \eqn{\boldsymbol{\eta}_{t}} is a vector of latent random variables
#'   at time \eqn{t},,
#'   and \eqn{\boldsymbol{\varepsilon}_{t}}
#'   is a vector of random measurement errors
#'   at time \eqn{t},
#'   while \eqn{\boldsymbol{\nu}} is a vector of intercept,
#'   \eqn{\boldsymbol{\Lambda}} is a matrix of factor loadings,
#'   and \eqn{\boldsymbol{\Theta}} is the covariance matrix of
#'   \eqn{\boldsymbol{\varepsilon}}.
#'
#'   The dynamic structure is given by
#'   \deqn{
#'     \boldsymbol{\eta}_{t}
#'     =
#'     \boldsymbol{\alpha}
#'     +
#'     \boldsymbol{\beta}
#'     \boldsymbol{\eta}_{t - 1}
#'     +
#'     \boldsymbol{\zeta}_{t}
#'     \quad
#'     \mathrm{with}
#'     \quad
#'     \boldsymbol{\zeta}_{t}
#'     \sim
#'     \mathcal{N}
#'     \left(
#'     \mathbf{0},
#'     \boldsymbol{\Psi}
#'     \right)
#'   }
#'   where \eqn{\boldsymbol{\eta}_{t}}, \eqn{\boldsymbol{\eta}_{t - 1}},
#'   and \eqn{\boldsymbol{\zeta}_{t}} are random variables
#'   and \eqn{\boldsymbol{\alpha}}, \eqn{\boldsymbol{\beta}},
#'   and \eqn{\boldsymbol{\Psi}} are model parameters.
#'   \eqn{\boldsymbol{\eta}_{t}} is a vector of latent variables
#'   at time \eqn{t}, \eqn{\boldsymbol{\eta}_{t - 1}}
#'   is a vector of latent variables at
#'   \eqn{t - 1},
#'   and \eqn{\boldsymbol{\zeta}_{t}} is a vector of dynamic noise
#'   at time \eqn{t} while \eqn{\boldsymbol{\alpha}}
#'   is a vector of intercepts,
#'   \eqn{\boldsymbol{\beta}} is a matrix of autoregression
#'   and cross regression coefficients,
#'   and \eqn{\boldsymbol{\Psi}} is the covariance matrix of
#'   \eqn{\boldsymbol{\zeta}_{t}}.
#'
#' @param data Numeric matrix.
#'   `time` by `k` data matrix.
#' @param Lambda Numeric matrix.
#'   Measurement or observation matrix.
#' @param mu0 Numeric matrix.
#'   Initial state mean vector.
#' @param Sigma0 Numeric matrix.
#'   Initial state covariance matrix.
#' @param beta Numeric matrix.
#'   State transition matrix.
#' @param chol_psi Numeric matrix.
#'   Cholesky decomposition of the state error covariance matrix Psi.
#' @param chol_theta Numeric matrix.
#'   Cholesky decomposition of the  observation error covariance matrix Theta.
#'
#' @return List of filtered state variables and other Kalman filter results.
#'
#' @examples
#' data <- dat_univ_p1[, "y", drop = FALSE]
#' kalman <- KFilterP1(
#'   data = data,
#'   Lambda = matrix(1),
#'   mu0 = matrix(0),
#'   Sigma0 = matrix(1),
#'   beta = matrix(0.8),
#'   chol_psi = matrix(1),
#'   chol_theta = matrix(1)
#' )
#' str(kalman)
#'
#' data <- dat_multiv_p1[, c("y1", "y2"), drop = FALSE]
#' kalman <- KFilterP1(
#'   data = data,
#'   Lambda = diag(2),
#'   mu0 = matrix(data = 0, nrow = 2),
#'   Sigma0 = diag(2),
#'   beta = diag(x = 0.8, nrow = 2, ncol = 2),
#'   chol_psi = chol(diag(2)),
#'   chol_theta = chol(diag(2))
#' )
#' str(kalman)
#'
#' @family Kalman Filter for State Space Models Functions
#' @keywords kalmanSSM kalman
#' @export
KFilterP1 <- function(data, Lambda, mu0, Sigma0, beta, chol_psi, chol_theta) {
    .Call(`_kalmanSSM_KFilterP1`, data, Lambda, mu0, Sigma0, beta, chol_psi, chol_theta)
}

